function init(obj, df, cf)
% Read input files and perform initialization.
%
% $Id$

% process data file
obj.val   = [hdf5read(cf, '/bc/bv_left'), ...
             hdf5read(cf, '/bc/bv_right'), ...
             hdf5read(cf, '/bc/bv_bottom'), ...
             hdf5read(cf, '/bc/bv_top')];
obj.free  = [hdf5read(cf, '/bc/bv_left_free'), ...
             hdf5read(cf, '/bc/bv_right_free'), ...
             hdf5read(cf, '/bc/bv_bottom_free'), ...
             hdf5read(cf, '/bc/bv_top_free')];

end